import * as autosaveDialog from './autosaveDialog/autosaveDialog.module';
import * as breakpoints from './breakpoints/breakpoints.module';
import * as componentValidator from './componentValidator/componentValidator.service';
import * as contentProvider from './contentProvider/contentProvider.service';
import * as dialog from './dialog/dialog.service';
import * as documentWrapper from './documentWrapper/documentWrapper.service';
import * as jquery from './jquery/jquery.service';
import * as templateLoader from './templateLoader/templateLoader.service';
import * as windowWrapper from './windowWrapper/windowWrapper.service';
export { autosaveDialog, breakpoints, componentValidator, contentProvider, dialog, documentWrapper, jquery, templateLoader, windowWrapper };
export declare var moduleName: string;
